alias apt-search='apt-cache search'
alias apt-install='sudo apt-get install'
alias apt-update='sudo apt-get update'
alias apt-upgrade='sudo apt-get upgrade'

alias virls='sudo virsh list --all'
alias vircon='sudo virsh console'
alias virxml='sudo virsh dumpxml'
alias virup='sudo virsh start'
alias virdown='sudo virsh destroy'

alias ll='ls -l'
alias la='ls -la'
